import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { WalletChildrenProvider } from "./_components/wallet";
import { TRPCReactProvider } from "~/trpc/react";
import { PresaleProvider } from "~/context/PresaleContext";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <WalletChildrenProvider>
            <PresaleProvider>{children}</PresaleProvider>
          </WalletChildrenProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
